<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Gcam.Core\Gcam.Core.csproj" />
    <ProjectReference Include="..\Gcam.Configuration\Gcam.Configuration.csproj" />
    <ProjectReference Include="..\Gcam.Masks\Gcam.Masks.csproj" />
    <ProjectReference Include="..\Gcam.Detector\Gcam.Detector.csproj" />
    <ProjectReference Include="..\Gcam.Decoding\Gcam.Decoding.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
