<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Genoray.MonteCarlo.Wpf</RootNamespace>
    <AssemblyName>Genoray.MonteCarlo.Wpf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WPF" Version="5.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Genoray.MonteCarlo.Core\Genoray.MonteCarlo.Core.csproj" />
    <ProjectReference Include="..\Genoray.MonteCarlo.Configuration\Genoray.MonteCarlo.Configuration.csproj" />
    <ProjectReference Include="..\Genoray.MonteCarlo.Detector\Genoray.MonteCarlo.Detector.csproj" />
    <ProjectReference Include="..\Genoray.MonteCarlo.Decoding\Genoray.MonteCarlo.Decoding.csproj" />
    <ProjectReference Include="..\Genoray.MonteCarlo.Masks\Genoray.MonteCarlo.Masks.csproj" />
    <ProjectReference Include="..\Genoray.MonteCarlo.Simulation\Genoray.MonteCarlo.Simulation.csproj" />
  </ItemGroup>

</Project>
