<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Genoray.MonteCarlo.Core\Genoray.MonteCarlo.Core.csproj" />
    <ProjectReference Include="..\Genoray.MonteCarlo.Configuration\Genoray.MonteCarlo.Configuration.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
